# Generated by Django 6.0.4 on 2026-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Osoncorp', max_length=200)),
                ('favicon_image', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('favicon_url', models.URLField(blank=True, help_text='Favicon URL (if no image uploaded)', null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
